FROM nginx:alpine

# 复制门户静态文件
COPY portal-static/static/ /usr/share/nginx/html/

# 复制 nginx 配置
COPY docker/nginx.portal.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
